### ISSUE TITLE
[Live Betting Test]: Live Bet stuck in 'Live', unable to be settled.

### ISSUE THREAD

**Issue by Duckarooni** [Azuro-protocol/Live-Betting-Bug-Report#22]
### Contact Details

shwnn98@gmail.com

### Your Wallet Address

0x4Bf891E8fddd955AC90c437e8F0c6Fa814067566

### Testing Scenario Conducted

Bug Patterns

### Test Description

Created this bet on 7 March for Amur vs Metallurg Hockey game. The game ended in Amur's win. However, it has been over a day and the bet has not yet been settled and the status of the games are still 'Live'.

![unable-to-settle](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/162700089/8c8f668f-0a75-40b4-8450-f5ac9c43085d)

Screenshot above taken at the moment of this post, on 8 March 1120AM UTC.

### Observed Behavior

My bets are unable to be settled, status remains in 'Live'.

### Expected Behavior

The status of the bet to be changed from 'Live' to 'Pending Resolution'. The bet to be settled within a few hours.

### Reproducibility of the Issue

Happened for this particular game, unable to reproduce.

**Comment by Duckarooni** [comment]
Screenshot above taken at the moment of this post, on 8 March 1120AM UTC.

**Comment by Duckarooni** [comment]
Reported this yesterday to Bookmaker.xyz as well, and it seems to have been solved with the latest update. My bets are now settled.

**Comment by layer-0** [comment]
Will be marked as already reported or not an issue mate, better not put time into Azuro.

**Comment by Avvrik** [comment]
Yes, this has been a delay on the data provider's side
