### ISSUE TITLE
[Live Betting Test]:  match progress is not displayed in live

### ISSUE THREAD

**Issue by SAVVAGEVLG** [Azuro-protocol/Live-Betting-Bug-Report#3]
### Contact Details

savvagmir@gmail.com

### Your Wallet Address

0x845eEF6ED5376B1996991686E585ad21F103c818

### Testing Scenario Conducted

System Flaw Exploration

### Test Description

I opened a live quote for the match Basaksahir Kayserispor Turkish Super League, where Basaksahir are the clear favorite, but during the match they lost and the odds were 10 on them

### Observed Behavior

odds of 10 on the clear favorite, but without opening the additional tab I didn’t understand what was going on

### Expected Behavior

a banner with the names of the teams and their series of matches before the match, their live result with mini-statistics was displayed

### Reproducibility of the Issue

no

### Additional Information

it would be convenient to add live scores, shots on goal, corners, cards, possession

**Comment by Avvrik** [comment]
Thank you for your suggestion. We're aware of the convenience this feature brings to the table. However, this is not an issue but rather an improvement idea.
