### ISSUE TITLE
[Live Betting Test]: Cant place any bet Stress Testing Schedule

### ISSUE THREAD

**Issue by pawelff** [Azuro-protocol/Live-Betting-Bug-Report#38]
### Contact Details

pawe.93945@gmail.com

### Your Wallet Address

0xea9c63b4abe4302e93272f4ed479f9b41ffa242b

### Testing Scenario Conducted

Bug Patterns

### Test Description

I wanted to participate in Stress Testing Schedule on Football Euro Poland - Estonia event. The issue is I cant place any bet. There is always "some problem".

### Observed Behavior

Oops popup on bookmaker

### Expected Behavior

Placed bet

### Reproducibility of the Issue

Simple live bet, more users on discord reported the same issue

### Additional Information

![image](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/41366728/ea262704-6990-4a6f-8f6d-818d559707f4)

**Comment by 0xJimbo** [comment]
Same problem here
