### ISSUE TITLE
All live events are locked [Live Betting Test]: 

### ISSUE THREAD

**Issue by bagay** [Azuro-protocol/Live-Betting-Bug-Report#4]
### Contact Details

bagaymu@gmail.com

### Your Wallet Address

0x00fCDD680C969B15432d8f732CC0d4F991DbbCE8

### Testing Scenario Conducted

Bug Patterns

### Test Description

I can't place any bet, because all events are locked and not getting unlocked since I start testing. One hour already

### Observed Behavior

Impossible to bet
![Снимок экрана 2024-02-22 005535](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/31293885/d5bba917-f923-46bf-821e-e35cf60bef0c)

### Expected Behavior

I expected to place a bet, but it is impossible

### Reproducibility of the Issue

It is always like that. Still didn't place any bet

**Comment by Avvrik** [comment]
The issue appears to refer to the interface's method of presenting the events, not to the Azuro protocol.
