### ISSUE TITLE
[Live Betting Test]: Some tennis players have club logos

### ISSUE THREAD

**Issue by layer-0** [Azuro-protocol/Live-Betting-Bug-Report#47]
### Your Wallet Address

0x9bdFF9f83216d82f387e8Bb0866c5A92273B6437

### Testing Scenario Conducted

Bug Patterns

### Test Description

Was checking tennis options and noticed club logos were used while tennis players normally have no logo.

### Observed Behavior

Club logos placed for certain tennis players, see screens:

![Untitled 3](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/3d344ca1-035c-48cd-881c-2c4213db4627)
![Untitled 1](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/f8689911-2c0d-4322-bec7-0f768bbed282)
![Untitled 2](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/536c21fd-0687-4d34-a72e-a6cd21432128)
![Untitled 4](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/1429ecfd-b072-4c3a-9a86-aaccc88e83c9)
![Untitled 5](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/7d54a89e-e86b-48b6-b85a-4868d7772f11)

### Expected Behavior

N/A

### Reproducibility of the Issue

Depening if Azuro updates it.

**Comment by layer-0** [comment]
Hi, at https://github.com/Azuro-protocol/Live-Betting-Bug-Report/issues/28 was similar as of club logos and was marked as low. So think this should also be marked as low?

**Comment by TimTheTeim** [comment]
man fuck you, there was no need to snitch
