### ISSUE TITLE
[Live Betting Test]: cannot use live options with firmware protected (Trezor) wallet

### ISSUE THREAD

**Issue by layer-0** [Azuro-protocol/Live-Betting-Bug-Report#49]
### Your Wallet Address

0x9bdFF9f83216d82f387e8Bb0866c5A92273B6437

### Testing Scenario Conducted

Bug Patterns

### Test Description

Testing live betting with hardware protected wallet.

### Observed Behavior

Cannot claim test tokens or place live test bets anymore with firmware (Trezor) protected wallet. Keeps loading and nothing happens while logged into Metamask firmware protected wallet.
![4](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/2dfcaf6f-3b68-4e2e-a0f9-1eccbb153e14)
If going back getting this screen:
![0](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/41c7dd2d-6445-496d-888e-b7626b11e7d5)

### Expected Behavior

N/A

### Reproducibility of the Issue

N/A

**Comment by layer-0** [comment]
Keeps loading and nothing happens.

**Comment by Yiraxa938** [comment]
You still facing the same issues??

**Comment by layer-0** [comment]
Hi,

Saw it was marked as no issue, but at the time it was not working, can check later when have some tokens on firmware account if it works now.

Saw that one of my entries was marked as low, but unsure received reward of Azuro score? Can you check? My address: 0x9bdFF9f83216d82f387e8Bb0866c5A92273B6437
https://github.com/Azuro-protocol/Live-Betting-Bug-Report/issues/12
________________________________

**Comment by Trezor-29Mod1** [comment]
Sorry for the inconvenience you should create a ticket here [Ticket](https://discord.gg/k3XYb5BShR) at Trezor discord channel about the issues you're facing.
