### ISSUE TITLE
[Live Betting Test]: Placing a bet

### ISSUE THREAD

**Issue by phakornkt** [Azuro-protocol/Live-Betting-Bug-Report#5]
### Contact Details

phakorncto@gmail.com

### Your Wallet Address

0xB74Cb1Aec2AA76038B24F7CC9D6f07b380a1F812
![Capture](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/158077983/f2cee13c-2cab-4a72-818e-baffa3cf7000)

### Testing Scenario Conducted

System Flaw Exploration

### Test Description

I often encounter problems with placing bets. I feel like when placing bets it takes a long time to complete. I would like it to be faster and more stable. This is the case I encountered in actual use. As for the live test when placing bets, I saw that there were some places where bets could not be placed. I saw that they were not stable enough to place bets. I missed that opportunity in the case that I had time left to place bets. Not much before the game started and when I was about to place a bet but couldn't, it made me realize that I was a little bored.
![Capture](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/158077983/165c2c5c-ce16-4c9a-9812-991d3b124a25)

### Observed Behavior

![1](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/158077983/9aa1cd92-0ccb-4c30-a3d3-be5ca8448e72)
For me, it is a bet that sometimes occurs and there are bugs or errors, or sometimes it doesn't work smoothly at all, causing it to take a long time to place the bet. It rotates like in the picture I attached and after a while it will say "Error".

### Expected Behavior

Now that I've been using it for about 2-3 weeks, I'd like to be able to use the stable more quickly so that I don't miss out on placing bets. That's my opinion. Right now I've only encountered this problem. If I have any problems using it, I'll keep reporting.

### Reproducibility of the Issue

I think the problem will definitely recur because it is the system's instability and stability, or maybe it's the internet or the signal. I'm not sure where it comes from, but I think it happened. It may be a bug or a glitch in the system. I think it's like that. I don't understand much about the system, but I think I'd like it to be more stable. Everyone likes it. Fast and bug-free, I'm one of them as well.

**Comment by Avvrik** [comment]
This issue refers to the interface's method of displaying error messages that arise from either wallet or connections issues.
