### ISSUE TITLE
[Live Betting Test]: Free bets seem to stay in the system (after used them)

### ISSUE THREAD

**Issue by layer-0** [Azuro-protocol/Live-Betting-Bug-Report#55]
### Your Wallet Address

0x9bdFF9f83216d82f387e8Bb0866c5A92273B6437

### Testing Scenario Conducted

Bug Patterns

### Test Description

Free bets seem to stay in system after using them.

### Observed Behavior

The free bets keep appearing, when selecting, it will not work of course as already used them so they are expired, but they keep popping up, noticed this with different free bets on different projects.
![5](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/38277909-36c5-4ecc-bb0c-e970904d1cd8)
![5555](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/f5fbefb9-52da-48c2-99b9-2777885946bd)

### Expected Behavior

N/A

### Reproducibility of the Issue

N/A

**Comment by TimTheTeim** [comment]
This has been already reported, as it is not a bug, just a UI error
