### ISSUE TITLE
[Live Betting Test]: Critical issue with the bet system 

### ISSUE THREAD

**Issue by Wisdomdc** [Azuro-protocol/Live-Betting-Bug-Report#58]
### Contact Details

wisdomd24462@gmail.com

### Your Wallet Address

0x21A5F16723b218880869e148E67bfC06354301eA

### Testing Scenario Conducted

Bug Patterns

### Test Description

Odds discrepancy 
![IMG_20240513_154823_384](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/118587622/f20f428e-cd30-4053-a394-74f15c1aa77b)

### Observed Behavior

Total odds gets reduce by over 50% anytime I increase my stake amount 
![IMG_20240513_154826_376](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/118587622/6952e0e5-79fd-4d8e-a742-ff9c36f93a90)

### Expected Behavior

My possible win should increase by x2 when I increase my stake amount by x2 and not the opposite
![IMG_20240513_154828_196](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/118587622/79bcefee-484d-4d0c-9311-df13e323b6ba)

### Reproducibility of the Issue

To address this, Azuro should adjust their odds calculation algorithm to ensure that the relationship between stake amount and odds remains consistent across all betting scenarios.

**Comment by Wisdomdc** [comment]
@player00 What do you mean by not an issue. Did you properly go through my report?
I have an issue with my report being flagged as not an issue. By the way, this is no longer about the points I'll get from the report.

I have only experienced this issue with Azuro and never with any other bookmaker. When placing a bet on Azuro, if you multiply your stake, the bet odds and potential winnings keep getting reduced. It decreases with each increase, and sometimes it even reduces by over 50%. For example, if I was going to win $1,000 with a $10 stake and I increase my stake amount from $10 to $20, my potential win gets reduced to $500-700 instead of $2,000. This is undoubtedly an issue and a clear one, so I can’t understand why my report is flagged as not an issue. @Avvrik check this

**Comment by player00** [comment]
@Wisdomdc Hello!
1. The case you reported relates to combo betting, not live betting.
2. This is actually an expected behavior, related to the nuances of liquidity distribution between conditions. You can try to get a bigger possible win by adding or removing different conditions to the combo.
