### ISSUE TITLE
[Live Betting Test]:  Use EIP712 rather than vanilla eth_sign 

### ISSUE THREAD

**Issue by Luigy-Lemon** [Azuro-protocol/Live-Betting-Bug-Report#6]
### Contact Details

luigy_lemon@protonmail.com

### Your Wallet Address

0xc44caeb7F0724A156806664d2361fD6f32a2d2C8

### Testing Scenario Conducted

Bug Patterns

### Test Description

When live betting in the mumbai testnet I submit a new bet.

### Observed Behavior

When a new bet is submitted there is a request to eth_sign the bet order.

### Expected Behavior

I would expect a more modern signature format to be used. EIP712 is a preferale signature method as it extends on the vanilla eth_sign but allows the user to validate in a readable way what exactly they are signing, instead of a simple hash.

### Reproducibility of the Issue

Any new bet in the live market on mumbai

### Additional Information
![image](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/35468346/733525fe-e28f-4ceb-beab-df3d65867d73)

_No response_

**Comment by Avvrik** [comment]
Score added: https://api.azuro.org/score/0xc44caeb7F0724A156806664d2361fD6f32a2d2C8/transactions
