### ISSUE TITLE
[Live Betting Test]: 6 cents disappeared from my balance. 

### ISSUE THREAD

**Issue by bagay** [Azuro-protocol/Live-Betting-Bug-Report#7]
### Contact Details

bagaymu@gmail.com

### Your Wallet Address

0x00fCDD680C969B15432d8f732CC0d4F991DbbCE8

### Testing Scenario Conducted

Bug Patterns

### Test Description

I had 2000$ on my account exactly and all my bets were exact numbers. Now there is 6 cents missing on my balance.
![Uploading Снимок экрана 2024-02-22 220936.png…]()

### Observed Behavior

just checked my balance it wasn't correct

### Expected Behavior

exact amount on my balance

### Reproducibility of the Issue

It is still showing wrong numbers

**Comment by Avvrik** [comment]
This is the wallet's relayer's fee that each user has an option to approve when sending a transaction.
